### PR TITLE
Initial Dutch translation

### PR DESCRIPTION
**Pull request by jerryhopper**

### CODE REVIEW

**Comment by flangfeldt** [comment]
Jerry, great effort!
I noticed you are mixing "je" and "u" a lot. Probably better to choose on of the two.
Also you seem to use lowercase for the beginning of sentences in some cases.

**Comment by jerryhopper** [comment]
@flangfeldt  when you adress a youngster - i would adress him with  'je'  
if its not clear if its a minor, 'u' is more appropreate.

but yes,  you are right.  translations need to be checked by at least 3 native speakers to get the best results. 
Therefore i suggested a translationtool that could help with that. see : https://github.com/FusionAuth/fusionauth-issues/issues/307

**Comment by flangfeldt** [comment]
@jerryhopper, translation tool is a great idea. I would need Dutch as well, that's why I had a "critical" look at it ;-)
Again thanks for the first version, must be some kind of record.

**Comment by robotdan** [comment]
@jerryhopper @flangfeldt you guys are awesome!!  Thanks!

**Pull request merged**
