### PR TITLE
fix(fr): missing two-factor index template translation keys

### PR DESCRIPTION
**Pull request by soullivaneuh**
This reverts commit 01c0154aacd932b4b55b10f30084ab77221dd8c5.

:warning: Those translation keys **ARE currently USED** by at least the `templates/account/two-factor/index.ftl` template file:

```
<th>${theme.message("method")}</th>
<th>${theme.message("value")}</th>
<th class="action">${theme.message("action")}</th>
```

@robotdan Please do not revert this change again, I did not add those keys for the fun.

I took the time to provide you french translations (#51) instead of keeping it on my local FusionAuth instance. It would be great to not see them reverted just after without any usage verification and description/justification on the commit body.

### CODE REVIEW

**Comment by mooreds** [comment]
@soullivaneuh the rollback was not intentional. It's unclear what happened, but we're looking into it.

**Comment by mooreds** [comment]
Ah, I see the issue now. You added new properties to `messages.properties` which our system overwrites (fusionauth-localization is not the primary source of that file).

Those values are not currently localizable. I'm looking into why.

I should have caught that in the PR review, my apologies.

**Comment by mooreds** [comment]
Hi @soullivaneuh I got to the bottom of this. The issue was the new keys you added. We can add them, but need to do it in a different manner.

I updated the documentation: https://github.com/FusionAuth/fusionauth-localization/blob/master/README.md#new-message-keys 

I also filed an issue: https://github.com/FusionAuth/fusionauth-issues/issues/1839 which should be picked up relatively soon and released.

At that point I'll merge this PR and we should be all good.

Sorry for the confusion.

**Comment by soullivaneuh** [comment]
Ok, thanks for the explanation.

**Comment by mooreds** [comment]
Merged because 1.39 has the files in the base message.properties file now.

**Pull request merged**
