### PR TITLE
Adds pt-BR localization

### PR DESCRIPTION
**Pull request by rapcal**
Please feel free to request any changes deemed necessary.

### CODE REVIEW

**Comment by robotdan** [comment]
Thanks for the contribution @rapcal !!

**Comment by rapcal** [comment]
@robotdan when do you think we'll be able to fetch the pt-BR locale [from the API](https://fusionauth.io/docs/v1/tech/reference/data-types/#locales)?

**Comment by robotdan** [comment]
We do not currently ship these locales in the default theme, although we could - and perhaps should. 

The way you currently access these localized values is by copying them into your theme. See https://github.com/FusionAuth/fusionauth-localization#how-to-use-a-translation. 

In the UI, `Customizations > Themes > Edit > Messages > Add localization`.

**Comment by rapcal** [comment]
> We do not currently ship these locales in the default theme, although we could - and perhaps should.
> 
> The way you currently access these localized values is by copying them into your theme. See https://github.com/FusionAuth/fusionauth-localization#how-to-use-a-translation.
> 
> In the UI, `Customizations > Themes > Edit > Messages > Add localization`.

Thanks a lot! Sorry to use the comments as if they were a support channel.... 🤦‍♂️

**Pull request merged**
