### PR TITLE
Added latest messages.

### PR DESCRIPTION
**Pull request by mooreds**
Addresses https://github.com/FusionAuth/fusionauth-localization/issues/48 ... for now.

### CODE REVIEW

**Comment by robotdan** [comment]
Is this just a manual sync of the version in `fusionauth-app` ? If we run `https://github.com/FusionAuth/fusionauth-localization/blob/master/update.rb` I think that will also fix up any other parts that require translation.

**Comment by mooreds** [comment]
Good point @robotdan . ran update.rb which updated the list of missing translations.

**Comment by mooreds** [comment]
But yes, it was a manual copy-commit-push

**Comment by mooreds** [comment]
Closing this since the 1.33.0 release means this PR is obsolete.

**Pull request closed without merging**
